version: '2.1'
services:
  db1:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "URLClass"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - db1:/var/lib/postgresql/data