version: '2.1'
services:
  Hash:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "URLClass"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - Hash:/var/lib/postgresql/data
volumes:
  Hash: